"""
Pydantic schemas for AI / LLM structured outputs and endpoint responses.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class SignalAnalysisOutput(BaseModel):
    """
    Structured operational analysis generated by the AI / LLM service.
    """

    summary: str = Field(
        ...,
        description="A concise executive summary of the operational issue.",
        examples=["Water dripping near server racks poses an electrical short-circuit hazard."],
    )
    category: str = Field(
        ...,
        description="Operational category assessed from the signal (maintenance, safety, infrastructure, etc.).",
        examples=["infrastructure"],
    )
    severity: str = Field(
        ...,
        description="Assessed operational severity level (low, medium, high, critical).",
        examples=["high"],
    )
    key_evidence: List[str] = Field(
        default_factory=list,
        description="Extracted key factual observations and physical evidence points.",
        examples=[["Dripping ceiling tile above Rack 4", "Basement sump pump alert"]],
    )
    recommended_attention: str = Field(
        ...,
        description="Immediate operational focus or investigative recommendation.",
        examples=["Dispatch facilities technician to isolate pipe overhead immediately."],
    )
    reasoning: str = Field(
        ...,
        description="Analytical reasoning explaining why this precursor matters and potential risks.",
        examples=["Water proximity to power distribution units creates an immediate fire hazard."],
    )


class SignalAnalysisResponse(BaseModel):
    """
    API Response model for POST /api/ai/analyze-signal/{signal_id}.
    """

    signal_id: int = Field(..., description="The ID of the analyzed signal")
    signal_title: str = Field(..., description="The title of the analyzed signal")
    status: str = Field(
        default="analyzed",
        description="Analysis state ('analyzed' or 'unavailable')",
    )
    analysis: Optional[SignalAnalysisOutput] = Field(
        default=None,
        description="Structured operational intelligence generated by the LLM",
    )
    model_used: Optional[str] = Field(
        default=None,
        description="The OpenAI model identifier used for analysis",
    )


class AIServiceUnavailableResponse(BaseModel):
    """
    Degraded response returned when OpenAI API key is not configured.
    """

    status: str = Field(
        default="unavailable",
        description="Service availability state",
    )
    message: str = Field(
        default="AI service is not configured. Please configure OPENAI_API_KEY.",
        description="Actionable guidance for configuring the service",
    )
